name: qiita_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  webview_flutter: ^4.2.4
  shared_preferences:
  connectivity_plus: ^4.0.1
  package_info_plus:
  flutter_dotenv:
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  flutter_keyboard_visibility: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - images/
    - .env
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
  uses-material-design: true
